---
format_version: 10
pipelines:
  ui-tests:
    group: tests
    materials:
      testrepo:
        git: https://github.com/ArtursJLazdins/ci_course
    environment_variables:
      TEST_ENVIRONMENT: dev
    stages:
      - test:
          jobs:
            test-chrome:
              tasks:
               - exec:
                   command: bash 
                   arguments: 
                    - -c 
                    - "Running UI tests ${TEST_ENVIRONMENT} environment and chrome browser"
            test-firefox:
              tasks:
               - exec:
                   command: bash 
                   arguments: 
                    - -c 
                    - "Running UI tests ${TEST_ENVIRONMENT} environment and firefox browser"
